// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8ajZ-oaFN05qV2dtzup8zSJFhwHCecMU',
    appId: '1:577083556500:web:9bddda4c0edf506ffcea81',
    messagingSenderId: '577083556500',
    projectId: 'fulttersession',
    authDomain: 'fulttersession.firebaseapp.com',
    storageBucket: 'fulttersession.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAygbc8ObQJzxHWnSQSpGCGOiRDsInvS5U',
    appId: '1:577083556500:android:445b2f9c0774ed60fcea81',
    messagingSenderId: '577083556500',
    projectId: 'fulttersession',
    storageBucket: 'fulttersession.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7hNsjr2ox3nCdUQa5x7vJN9UVmQnomNo',
    appId: '1:577083556500:ios:d93a2e4d686a7fe0fcea81',
    messagingSenderId: '577083556500',
    projectId: 'fulttersession',
    storageBucket: 'fulttersession.firebasestorage.app',
    iosBundleId: 'com.example.cyberlog2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7hNsjr2ox3nCdUQa5x7vJN9UVmQnomNo',
    appId: '1:577083556500:ios:d93a2e4d686a7fe0fcea81',
    messagingSenderId: '577083556500',
    projectId: 'fulttersession',
    storageBucket: 'fulttersession.firebasestorage.app',
    iosBundleId: 'com.example.cyberlog2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8ajZ-oaFN05qV2dtzup8zSJFhwHCecMU',
    appId: '1:577083556500:web:86ee723b51c4f8dafcea81',
    messagingSenderId: '577083556500',
    projectId: 'fulttersession',
    authDomain: 'fulttersession.firebaseapp.com',
    storageBucket: 'fulttersession.firebasestorage.app',
  );
}
